variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "${DOCKER_TLS_CERTDIR}/client"

stages:
  - module-pipelines

frontend:
  stage: module-pipelines
  trigger:
    include:
      - "/frontend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - frontend/**/*

backend:
  stage: module-pipelines
  trigger:
    include:
      - "/backend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - backend/**/*

deploy:
  stage: module-pipelines
  trigger:
    include:
      - "/helm/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - frontend/**/*
      - backend/**/*
      - helm/**/*
