apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
  sessionAffinity: None
  type: {{ .Values.selectorType }}
