---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-docker-config-secret
  namespace: {{ .Values.global.namespace }}
data:
  .dockerconfigjson: {{ tpl .Values.backend.dockerconfigjson . }}
type: kubernetes.io/dockerconfigjson
