---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.resourceStorage }}
  accessModes:
    - ReadWriteOnce
  csi:
    driver: {{ .Values.csiDriver }}
    fsType: {{ .Values.csiFsType }}
    volumeHandle: {{ .Values.grafanaDiskId }}
  storageClassName: {{ .Values.storageClassName }}
