apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: dumplings-store
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kdv@skillvrn.ru
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
