---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Values.global.namespace }}
data:
  nginx.conf: |
    server {

      listen {{ .Values.frontend.service.port }};

      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api/ {
          proxy_pass http://backend:{{.Values.frontend.service.backendPort }}/;
      }
    }
