---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
    environment: {{ .Values.frontend.lables.environment }}
spec:
  type: {{ .Values.frontend.service.specType }}
  ports:
    - port: {{.Values.frontend.service.port }}
      protocol: TCP
      targetPort: {{.Values.frontend.service.port }}
  selector:
    app: {{ .Chart.Name }}
